# Generated by Django 4.2.9 on 2024-01-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionproducts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='fashionproductlist',
            name='colors',
            field=models.ManyToManyField(to='fashionproducts.color'),
        ),
        migrations.AddField(
            model_name='fashionproductlist',
            name='sizes',
            field=models.ManyToManyField(to='fashionproducts.size'),
        ),
    ]
