# Generated by Django 5.0.1 on 2024-02-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionproducts', '0002_fields_subimages_remove_fashionproductlist_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='varients',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
