# Generated by Django 5.0.1 on 2024-02-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionproducts', '0003_varients_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionproductlist',
            name='brand',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
