# Generated by Django 4.2.9 on 2024-01-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_functionproductlist_topproductlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FunctionProductList',
            new_name='FashionProductList',
        ),
    ]
