# Generated by Django 4.1 on 2024-01-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_functionproductlist_fashionproductlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fashionproductlist',
            options={'verbose_name_plural': 'Fashionproductlist'},
        ),
    ]
