# Generated by Django 4.1 on 2024-01-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_fashionproductlist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestproductlist',
            name='slug',
            field=models.SlugField(default='products', max_length=225),
        ),
        migrations.AddField(
            model_name='fashionproductlist',
            name='slug',
            field=models.SlugField(default='products', max_length=225),
        ),
        migrations.AddField(
            model_name='topproductlist',
            name='slug',
            field=models.SlugField(default='products', max_length=225),
        ),
    ]
