# Generated by Django 4.1 on 2024-01-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_bestproductlist_slug_fashionproductlist_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestproductlist',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='fashionproductlist',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='topproductlist',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='bestproductlist',
            name='image2',
            field=models.ImageField(default='default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='bestproductlist',
            name='image3',
            field=models.ImageField(default='default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='bestproductlist',
            name='image4',
            field=models.ImageField(default='default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='bestproductlist',
            name='image5',
            field=models.ImageField(default='default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='bestproductlist',
            name='size',
            field=models.CharField(default=0, max_length=225),
        ),
        migrations.AddField(
            model_name='fashionproductlist',
            name='image2',
            field=models.ImageField(default='default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='fashionproductlist',
            name='image3',
            field=models.ImageField(default='default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='fashionproductlist',
            name='image4',
            field=models.ImageField(default='default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='fashionproductlist',
            name='image5',
            field=models.ImageField(default='default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='fashionproductlist',
            name='size',
            field=models.CharField(default=0, max_length=225),
        ),
        migrations.AddField(
            model_name='topproductlist',
            name='image2',
            field=models.ImageField(default='default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='topproductlist',
            name='image3',
            field=models.ImageField(default='default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='topproductlist',
            name='image4',
            field=models.ImageField(default='default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='topproductlist',
            name='image5',
            field=models.ImageField(default='default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='topproductlist',
            name='size',
            field=models.CharField(default=0, max_length=225),
        ),
    ]
