# Generated by Django 4.1 on 2024-01-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_image_bestproductlist_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestproductlist',
            name='size',
            field=models.CharField(choices=[('XS', 'Xtra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra Large')], max_length=2),
        ),
        migrations.AlterField(
            model_name='fashionproductlist',
            name='size',
            field=models.CharField(choices=[('XS', 'Xtra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra Large')], max_length=2),
        ),
        migrations.AlterField(
            model_name='topproductlist',
            name='size',
            field=models.CharField(choices=[('XS', 'Xtra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra Large')], max_length=2),
        ),
    ]
