# Generated by Django 4.1 on 2024-01-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_bestproductlist_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestproductlist',
            name='size',
        ),
        migrations.RemoveField(
            model_name='fashionproductlist',
            name='size',
        ),
        migrations.RemoveField(
            model_name='topproductlist',
            name='size',
        ),
    ]
