# Generated by Django 4.2.9 on 2024-01-14 16:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_remove_bestproductlist_size_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='CategoryProducts',
        ),
    ]
