# Generated by Django 4.2.9 on 2024-01-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_product_categoryproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproducts',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Category-products'},
        ),
    ]
