# Generated by Django 4.2.9 on 2024-01-16 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_rename_image_categoryproducts_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name2', models.CharField(max_length=50)),
                ('name3', models.CharField(max_length=50)),
                ('name4', models.CharField(max_length=50)),
                ('name5', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.bestproductlist')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.bestproductsize')),
            ],
        ),
        migrations.AddField(
            model_name='bestproductlist',
            name='sizes',
            field=models.ManyToManyField(through='product.ProductSize', to='product.bestproductsize'),
        ),
    ]
