# Generated by Django 4.2.9 on 2024-01-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_delete_bestproductlist_delete_bestproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopProductList',
        ),
        migrations.DeleteModel(
            name='TopProducts',
        ),
    ]
