# Generated by Django 4.2.9 on 2024-01-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_delete_topproductlist_delete_topproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FashionProductList',
        ),
        migrations.DeleteModel(
            name='FashionProducts',
        ),
    ]
