# Generated by Django 5.0.1 on 2024-02-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default_image.png', upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'bankdiscounts',
            },
        ),
        migrations.CreateModel(
            name='ProductDiscounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('image', models.ImageField(default='default_image.png', upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'productdiscounts',
            },
        ),
    ]
