# Generated by Django 5.0.1 on 2024-02-19 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=225)),
                ('mobile', models.CharField(max_length=225)),
                ('addressLine1', models.CharField(max_length=225)),
                ('addressLine2', models.CharField(max_length=225)),
                ('landmark', models.CharField(max_length=225)),
                ('pincode', models.CharField(max_length=225)),
                ('townOrCity', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
