# Generated by Django 4.1 on 2024-01-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default_image.png', upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'sliders',
            },
        ),
    ]
