# Generated by Django 4.2.9 on 2024-01-23 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashionproducts', '0006_rename_image1_subimages_image_and_more'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='fashionproducts.types'),
        ),
        migrations.AddField(
            model_name='cart',
            name='varient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varient', to='fashionproducts.varients'),
        ),
    ]
