# Generated by Django 5.0.1 on 2024-02-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Packed', 'Packed'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], default='processing', max_length=50),
        ),
    ]
